name: Test LocalGov Drupal

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Clone drupal_container
        uses: actions/checkout@v2
        with:
          repository: localgovdrupal/drupal-container
          ref: master

      - name: Create LocalGovDrupal project
        run: composer create-project --stability dev localgovdrupal/localgov-project html

      - name: Checkout localgov_guides branch to test
        uses: actions/checkout@v2
        with:
          path: html/web/modules/contrib/localgov_guides

      - name: Start Docker environment
        run: docker-compose up -d

      - name: Run tests
        run: ./run-tests.sh
        shell: bash
